# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convolve_cpp <- function(supp1, probs1, supp2, probs2) {
    .Call('_ddfr_convolve_cpp', PACKAGE = 'ddfr', supp1, probs1, supp2, probs2)
}

