# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convolve two discrete distributions
#'
#' `convolve_cpp` returns the convolution of two discrete distributions given
#' their supports and the corresponding probabilities.
#'
#' Some assumptions are made for the function to work properly which should be
#' followed. Most importantly, corresponding numeric vectors (e.g. `supp1` and
#' `probs1`) should have the same length.
#'
#' The function returns a list with components "support" and "probabilities"
#' which give the matching attributes of the convolution.
#'
#' @export
#' @param supp1,probs1 Numeric vectors.
#' @param supp2,probs2 Numeric vectors.
#' @return A list.
#' @examples
#' # Calculate the probability distribution of the sum of two six-sided dice
#' convolve_cpp((1:6), rep(1/6, 6), (1:6), rep(1/6, 6))
convolve_cpp <- function(supp1, probs1, supp2, probs2) {
    .Call(`_ddfr_convolve_cpp`, supp1, probs1, supp2, probs2)
}

